name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags: '*'

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    env:
      JULIA_NUM_THREADS: 2
    strategy:
      fail-fast: true
      matrix:
        experimental: [false]
        version:
          - '1.9'
          - '1.10'
        os:
          - ubuntu-latest
        arch:
          - x64
        include:
          - version: 'nightly'
            os: ubuntu-latest
            experimental: true
            arch: x64
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
        with:
          cache-registries: "true"
      - uses: julia-actions/julia-buildpkg@v1
      - name: Precompile project
        run: |
          julia --project -e '
            using Pkg
            Pkg.instantiate()
            Pkg.precompile()
          '
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        with:
          files: lcov.info

# vim: shiftwidth=2
